# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b56d0e4f6a9317aa7f4265d35ca6b9ab7f5a3de6809f55115851489812ebc025dc1d166a305d6c33e112dd91bb93f2136b95dae4bf6c86fa0ee5fc9443d5cc67

test:
  secret_key_base: 416455541091940bd5d81e22334ec0f88dc6b476aa4ce58646bd6969c8fb3410f306bcf789d9f1cbb8e1c380c5ac2fb9ec4f884a996c82d66131b1e75ac1a655

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
